### ISSUE TITLE
errors: I am not able to test the game

### ISSUE THREAD

**Issue by tempral** [horror/d2d-shooter_game#1]
[I posted the report in teeworlds forum](https://www.teeworlds.com/forum/viewtopic.php?pid=121013#p121013)

**Comment by horror** [comment]
I think you must downgrade your rake

**Comment by horror** [comment]
Or edit gem file, for updating rake version. Try goole for some deploy errors like this, its common problems

**Comment by tempral** [comment]
I tried to donwgrade rake or to edit gemfile, but in anycase the same error

```
C:\Sites\ht\app>rake db:migrate
(in C:/Sites/ht)
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/values/time_zone.rb:270: warning: circular argument reference - now

C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:52: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:56: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:60: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:79: warning: circular argument r
eference - reflection
rake aborted!
cannot load such file -- atk
C:/Sites/ht/config/application.rb:7:in `<top (required)>'
C:/Sites/ht/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

C:\Sites\ht\app>rake db:migrate --trace
(in C:/Sites/ht)
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/values/time_zone.rb:270: warning: circular argument reference - now

C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:52: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:56: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:60: warning: circular argument r
eference - reflection
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-3.2.13/lib/act
ive_record/associations/has_many_association.rb:79: warning: circular argument r
eference - reflection
rake aborted!
cannot load such file -- atk
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `block in require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:236:in `load_dependency'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/gdk3-3.2.1-x86-mingw32/lib/
gdk3.rb:19:in `<top (required)>'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `block in require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:236:in `load_dependency'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.13/lib/ac
tive_support/dependencies.rb:251:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/clutter-3.2.1-x86-mingw32/l
ib/clutter.rb:29:in `<top (required)>'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:82:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:82:in `block (2 levels) in require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:77:in `each'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:77:in `block in require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:66:in `each'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/
runtime.rb:66:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler.
rb:108:in `require'
C:/Sites/ht/config/application.rb:7:in `<top (required)>'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:5
5:in `require'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:5
5:in `require'
C:/Sites/ht/Rakefile:5:in `<top (required)>'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/rake_m
odule.rb:25:in `load'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/rake_m
odule.rb:25:in `load_rakefile'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:637:in `raw_load_rakefile'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:94:in `block in load_rakefile'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:165:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:93:in `load_rakefile'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:77:in `block in run'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:165:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/lib/rake/applic
ation.rb:75:in `run'
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.1.1/bin/rake:33:in
`<top (required)>'
C:/RailsInstaller/Ruby2.3.3/bin/rake:22:in `load'
C:/RailsInstaller/Ruby2.3.3/bin/rake:22:in `<main>'
```

**Comment by horror** [comment]
Please, check google for resolving any external lib version issues. I cant help you faster then google, becouse i not use ruby long time.
